-- USER SQL
CREATE USER "ERPDEMO01" IDENTIFIED BY "Oracle987654"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;
-- QUOTAS
ALTER USER "ERPDEMO01" QUOTA UNLIMITED ON "DBFS_DATA";
ALTER USER "ERPDEMO01" QUOTA UNLIMITED ON "DATA";
-- ROLES
GRANT "OML_DEVELOPER" TO "ERPDEMO01" ;
GRANT "DWROLE" TO "ERPDEMO01" ;
ALTER USER "ERPDEMO01" DEFAULT ROLE "OML_DEVELOPER","DWROLE";
/
-- USER SQL
CREATE USER "ERPDEMO02" IDENTIFIED BY "Oracle987654"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;
-- QUOTAS
ALTER USER "ERPDEMO02" QUOTA UNLIMITED ON "DBFS_DATA";
ALTER USER "ERPDEMO02" QUOTA UNLIMITED ON "DATA";
-- ROLES
GRANT "OML_DEVELOPER" TO "ERPDEMO02" ;
GRANT "DWROLE" TO "ERPDEMO02" ;
ALTER USER "ERPDEMO02" DEFAULT ROLE "OML_DEVELOPER","DWROLE";
/
-- USER SQL
CREATE USER "ERPDEMO03" IDENTIFIED BY "Oracle987654"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;
-- QUOTAS
ALTER USER "ERPDEMO03" QUOTA UNLIMITED ON "DBFS_DATA";
ALTER USER "ERPDEMO03" QUOTA UNLIMITED ON "DATA";
-- ROLES
GRANT "OML_DEVELOPER" TO "ERPDEMO03" ;
GRANT "DWROLE" TO "ERPDEMO03" ;
ALTER USER "ERPDEMO03" DEFAULT ROLE "OML_DEVELOPER","DWROLE";
/
-- USER SQL
CREATE USER "ERPDEMO04" IDENTIFIED BY "Oracle987654"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;
-- QUOTAS
ALTER USER "ERPDEMO04" QUOTA UNLIMITED ON "DBFS_DATA";
ALTER USER "ERPDEMO04" QUOTA UNLIMITED ON "DATA";
-- ROLES
GRANT "OML_DEVELOPER" TO "ERPDEMO04" ;
GRANT "DWROLE" TO "ERPDEMO04" ;
ALTER USER "ERPDEMO04" DEFAULT ROLE "OML_DEVELOPER","DWROLE";
/
-- USER SQL
CREATE USER "ERPDEMO05" IDENTIFIED BY "Oracle987654"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;
-- QUOTAS
ALTER USER "ERPDEMO05" QUOTA UNLIMITED ON "DBFS_DATA";
ALTER USER "ERPDEMO05" QUOTA UNLIMITED ON "DATA";
-- ROLES
GRANT "OML_DEVELOPER" TO "ERPDEMO05" ;
GRANT "DWROLE" TO "ERPDEMO05" ;
ALTER USER "ERPDEMO05" DEFAULT ROLE "OML_DEVELOPER","DWROLE";
/
